use_frameworks!

target 'Swift_SimpleNetworkLibrary_Example' do
  pod 'Swift_SimpleNetworkLibrary', :path => '../'

  target 'Swift_SimpleNetworkLibrary_ExampleTests' do
    inherit! :search_paths
    pod 'Swift_SimpleNetworkLibrary', :path => '../'
  end
end
